### ISSUE TITLE
Downloading File

### ISSUE THREAD

**Issue by halmonchaquayla** [learn-co-curriculum/dsc-generating-word-embeddings-lab#1]
I tried to download data for this lab at 'News_Category_Dataset_v2.json' but I get an error 
**ValueError: Unexpected character found when decoding 'NaN'**

However when I checked the file in the github page and used 'News_Category_Dataset_v2.zip' it seems to work.

**Comment by christine-egan42** [comment]
Checked instructions to make sure they indicated the file should be unzipped first -- looks good to go.
